# Generated by Django 4.2.7 on 2023-11-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_recetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=25)),
                ('titulacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=250)),
                ('ingredientes', models.CharField(max_length=250)),
                ('autor', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=25)),
                ('usuario', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
