# Generated by Django 4.2.7 on 2023-11-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_recetas', '0003_delete_cocinero_usuario_autor_alter_recetas_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetas',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='autor',
        ),
    ]
