# Generated by Django 4.2.7 on 2023-11-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_recetas', '0005_recetas_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetas',
            name='creador',
        ),
        migrations.AddField(
            model_name='recetas',
            name='autor',
            field=models.CharField(default='autor desconocido', max_length=25),
            preserve_default=False,
        ),
    ]
