# Generated by Django 4.2.7 on 2023-11-26 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control_recetas', '0006_remove_recetas_creador_recetas_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
