# Generated by Django 4.2.7 on 2023-11-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_recetas', '0008_alter_recetas_descripcion_alter_recetas_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='fecha',
            field=models.CharField(default='fecha desconocida', max_length=25),
        ),
    ]
